name: Master
on:
  push:
    branches:
      - master
jobs:
    testing:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/cache@v2
          with:
            path: '**/node_modules'
            key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
        - name: Install modules
          run: yarn
        - name: Run lint
          run: yarn lint
        - name: Run tests
          run: yarn test
